name: Build and Test

on:
    - pull_request
    - push

jobs:
    install_full_workspace:
        runs-on: ubuntu-latest

        env:
            UNSKIP_DECR: 'false' # do not decrypt the .env files

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Restore Yarn Cache
              id: root-yarn-cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Root (Lerna) Dependencies
              run: yarn install --ignore-scripts

            - name: Install Packages Dependencies
              run: yarn bootstrap
              env:
                  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
            #
            - name: Bootstrap CMS Database
              run: yarn boot
              working-directory: cms

            - name: Cache CMS Folder
              uses: actions/cache@v2
              id: cms-dir-cache
              with:
                  path: cms/
                  key: cms-${{github.sha}}-v2

            - name: Cache webhooks/strapi
              uses: actions/cache@v2
              id: strapi-dir-cache
              with:
                  path: webhooks/strapi
                  key: webhooks-strapi-${{github.sha}}

            - name: Cache search/cloudfare
              uses: actions/cache@v2
              id: search-cloudfare-cache
              with:
                  path: search/cloudfare
                  key: search-cloudfare-${{github.sha}}

    build_cms:
        runs-on: ubuntu-latest
        needs: install_full_workspace
        env:
            NODE_ENV: production
            UNSKIP_DECR: 'false'

        defaults:
            run:
                working-directory: cms

        steps:
            - name: restore cache
              uses: actions/cache@v2
              id: restore-cms-build
              with:
                  path: cms/
                  key: cms-${{github.sha}}-v2

            - name: build cms dashboard
              run: yarn build

    test_cms:
        runs-on: ubuntu-latest
        needs: install_full_workspace

        defaults:
            run:
                working-directory: cms
        steps:
            - name: restore cache
              uses: actions/cache@v2
              id: restore-cms-test
              with:
                  path: cms/
                  key: cms-${{github.sha}}-v2

            - name: API Tests
              run: yarn test

            - name: save tests code coverage
              uses: actions/upload-artifact@v2
              with:
                  name: backend-integration-test-coverage-${{github.sha}}
                  path: cms/coverage

    build_search_cloudfare:
        runs-on: ubuntu-latest
        needs: install_full_workspace
        env:
            NODE_ENV: production
        defaults:
            run:
                working-directory: search/cloudfare

        steps:
            - name: Restore search/cloudfare
              uses: actions/cache@v2
              id: restore-search-cloudfare-build
              with:
                  path: search/cloudfare
                  key: search-cloudfare-${{github.sha}}

            - name: Build worker.js
              run: yarn build

    build_webhook_hapi:
        runs-on: ubuntu-latest
        needs: install_full_workspace
        env:
            NODE_ENV: production
        defaults:
            run:
                working-directory: webhooks/strapi

        steps:
            - name: Restore webhooks/strapi cache
              uses: actions/cache@v2
              id: restore-webhook-strapi-build
              with:
                  path: webhooks/strapi
                  key: webhooks-strapi-${{github.sha}}

            - name: Build Hapi
              run: yarn build

    test_webhook_hapi:
        runs-on: ubuntu-latest
        needs:
            - install_full_workspace
        env:
            NODE_ENV: production
        defaults:
            run:
                working-directory: webhooks/strapi
        steps:
            - name: Restore webhooks/strapi cache
              uses: actions/cache@v2
              id: restore-webhook-strapi-test
              with:
                  path: webhooks/strapi
                  key: webhooks-strapi-${{github.sha}}

            - name: Test Hapi
              run: yarn test

    # install_dis:

    #     runs-on: ubuntu-latest
    #     env:
    #         UNSKIP_DECR: 'false'
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v2
    #           with:
    #               persist-credentials: false
    #         - name: Get DIS modules
    #           uses: actions/cache@v2
    #           id: cache
    #           with:
    #               path: ./*
    #               key: ${{ runner.os }}-dis6-${{ hashFiles('**/package.json') }}
    #         - name: Get Node
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: 14.x
    #         - name: Use npm version 7
    #           run: |
    #               npm install -g npm@7
    #         - name: Install dependencies
    #           run: npm ci
    #           if: steps.cache.outputs.cache-hit != 'true'
    #         - name: Install cms
    #           run: npm install --prefix cms
    #           if: steps.cache.outputs.cache-hit != 'true'
    #         - name: Cache all of the above
    #           uses: actions/cache@v2
    #           id: cache-dis
    #           with:
    #               path: ./*
    #               key: dis-${{github.sha}}
    # test_dis_unit:
    #     runs-on: ubuntu-latest
    #     needs: install_dis
    #     steps:
    #         - name: restore cache
    #           uses: actions/cache@v2
    #           id: restore-dis-test-unit
    #           with:
    #               path: ./*
    #               key: dis-${{github.sha}}
    #         - name: run unit tests
    #           run: npm run test:unit
    #         - name: save unit test code coverage
    #           uses: actions/upload-artifact@v2
    #           with:
    #               name: frontend-unit-test-coverage-${{github.sha}}
    #               path: coverage
    # test_dis_integration:
    #     runs-on: ubuntu-latest
    #     needs:
    #         - install_dis
    #         - install_full_workspace
    #     steps:
    #         - name: restore dis cache
    #           uses: actions/cache@v2
    #           id: restore-dis-test-integration
    #           with:
    #               path: ./*
    #               key: dis-${{github.sha}}
    #         - name: restore cms cache
    #           uses: actions/cache@v2
    #           id: restore-cms-dis-test
    #           with:
    #               path: cms
    #               key: cms
    #         - name: run integration tests
    #           run: npm run test:integration
    #         - name: save integration tests code coverage
    #           uses: actions/upload-artifact@v2
    #           with:
    #               name: frontend-integration-test-coverage-${{github.sha}}
    #               path: coverage
    # build_dis:
    #     runs-on: ubuntu-latest
    #     needs:
    #         - install_dis
    #     steps:
    #         - name: restore dis cache
    #           uses: actions/cache@v2
    #           id: restore-dis-test-integration
    #           with:
    #               path: ./*
    #               key: dis-${{github.sha}}
    #         - name: list everything
    #           run: |
    #               ls -a .
    #               ls cms/
    #         - name: Build NextJS
    #           run: |
    #               npm run server:testing & npm run build
