name: Scrape, Index and Upload to Cloudfare

on:
    push:
        # branches:
        #     - main

jobs:
    scrape_index_deploy:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              id: restore-puppeteer-node-modules
              with:
                  key: ${{runner.os}}-node-modules-v2.2-${{hashFiles('search/**/yarn.lock')}}
                  path: |
                      search/puppeteer/node_modules
                      search/cloudfare/node_modules
            #   restore-keys: |
            #       ${{runner.os}}-node-modules-v2
            #       ${{runner.os}}-node-modules-

            # - name: Install search/puppeteer node modules
            #   run: yarn install # not doing frozen lockfile because node_modules are already present
            #   working-directory: search/puppeteer

            # - name: Install search/cloudfare node modules
            #   run: yarn install
            #   working-directory: search/cloudfare

            # - name: Index and Scrape
            #   run: yarn start
            #   working-directory: search/puppeteer

            - name: Build Cloudfare Worker
              run: |
                  cd search/cloudfare
                  ls
                  rm -rf node_modules/
                  yarn install --force
                  yarn build
              env:
                  NODE_ENV: development
            #   working-directory: search/cloudfare
            - name: Publish to Cloudfare
              run: yarn deploy
              env:
                  CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
                  CF_API_TOKEN: 'VASFDSAFfasfasdf'
                  # CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  path: search/puppeteer/artifact
