name: Scrape, Index and Upload to Cloudfare

on:
    workflow_dispatch:
        inputs:
            dispatch_name:
                description: 'Dispatch Name'
                required: true
                default: '<enter any reason for manual dispatch>'
    schedule:
        - cron: '0 23 * * 0,3' # every sunday and wednesday at 11:00 pm'
    push:
        branches:
            - 'refactor/entire-project'

jobs:
    scrape_index_deploy:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              if: steps.restore-node-modules.outputs.cache-hit != 'true'
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Restore Yarn Cache
              id: root-yarn-cache
              if: steps.restore-node-modules.outputs.cache-hit != 'true'
              uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('search/**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            # - name: Restore cache
            #   uses: actions/cache@v2
            #   id: restore-puppeteer-node-modules
            #   with:
            #       key: ${{runner.os}}-node-modules-v2.2-${{hashFiles('search/**/yarn.lock')}}
            #       path: |
            #           search/puppeteer/node_modules
            #           search/cloudfare/node_modules
            #       restore-keys: |
            #           ${{runner.os}}-node-modules-v2
            #           ${{runner.os}}-node-modules-

            - name: Install search/puppeteer node modules
              run: yarn install --frozen-lockfile # not doing frozen lockfile because node_modules are already present
              working-directory: search/puppeteer
              env:
                  NODE_ENV: development

            - name: Show Trigger Dispatch
              run: |
                  echo "Dispatch Name: ${{ github.event.inputs.dispatch_name }} By ${{ github.actor }}"

            - name: Install search/cloudfare node modules
              run: yarn install --frozen-lockfile
              working-directory: search/cloudfare
              env:
                  NODE_ENV: development # do not skip devDependencies

            - name: Index and Scrape
              run: yarn start
              working-directory: search/puppeteer

            - name: Build Cloudfare Worker
              run: yarn build
              working-directory: search/cloudfare
            - name: Publish to Cloudfare
              run: |
                  yarn global add @cloudflare/wrangler
                  yarn deploy
              env:
                  CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
                  CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
              working-directory: search/cloudfare

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  path: search/puppeteer/artifact
