name: Scrape, Index and Upload to Cloudfare

on:
    push:
        # branches:
        #     - main

jobs:
    install_dirs:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              id: restore-puppeteer-node-modules
              with:
                  key: ${{runner.os}}-node-modules-${{hashFiles('search/puppeteer/yarn.lock')}}
                  path: search/puppeteer/node_modules
                  restore-keys: |
                      ${{runner.os}}-node-modules-

            - name: Install search/puppeteer modules
              run: yarn install --frozen-lockfile
              working-directory: search/puppeteer

            - name: Index and Scrape
              run: yarn start
              working-directory: search/puppeteer

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: indexed-extracted-${{github.sha}}
                  path: search/puppeteer/artifact
