name: Remaining to Do

on: push

jobs:
    todos:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Add/Remove ToDo as Issue
              uses: alstr/todo-to-issue-action@v2.4.1
              id: v2-todos
              with:
                  REPO: ${{ github.repository }}
                  BEFORE: ${{ github.event.before }}
                  SHA: ${{ github.sha }}
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LABEL: '// TODO'
                  COMMENT_MARKER: '//'
